version: '3.7' 

configs:
  mongodb_config:
    file: ./db/mongodb.conf

services:

  # Mongo DB
  mongo: 
    image: mongo:latest
    command: mongod --config /etc/mongodb.conf
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    configs:
      - source: mongodb_config
        target: /etc/mongodb.conf
    env_file:
      - .env
    networks:
      - backend_network



networks:
  backend_network:
    driver: bridge

