version: '3.7' 

configs:
  mongodb_config:
    file: ./db/mongodb.conf

services:

  # Mongo DB
  mongo: 
    image: mongo:latest
    command: mongod --config /etc/mongodb.conf
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    configs:
      - source: mongodb_config
        target: /etc/mongodb.conf
    env_file:
      - .env
    networks:
      - backend_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s



  # Rust Backend API
  backend_api:
    image: rust:1.73
    working_dir: /usr/src/backend_nuitinfo_2023
    volumes:
      - ./dependencies:/usr/src/cargohome
      - ./api:/usr/src/backend_nuitinfo_2023
    command: ["sh", "-c", "cargo install --path . && cargo run --release"]
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - backend_network
      - user_network
  
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./front/build:/usr/share/nginx/html
    networks:
      - user_network


networks:
  backend_network:
    driver: bridge
  user_network:
    driver: bridge

