version: '3.7' 

configs:
  mongodb_config:
    file: ./db/mongodb.conf

services:
  # Mongo DB
  mongo: 
    image: mongo:latest
    command: mongod --config /etc/mongodb.conf
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    configs:
      - source: mongodb_config
        target: /etc/mongodb.conf
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    networks:
      - backend_network
      

  # # Node.js
  nodejs:
    depends_on:
      - mongo
    image: node:latest
    volumes:
      - .env:/.env
      - .:/app
    working_dir: /app/api
    command: npm run dev
    ports:
      - "80:80"
    networks:
      - backend_network
      - user_network

networks:
  backend_network:
    driver: bridge
  user_network:
    driver: bridge

