version: '3.7' 

configs:
  mongodb_config:
    file: ./db/mongodb.conf

services:

  # Mongo DB
  mongo: 
    image: mongo:latest
    command: mongod --config /etc/mongodb.conf
    ports:
      - "27017:27017"
    volumes:
      - ./db/data:/data/db
    configs:
      - source: mongodb_config
        target: /etc/mongodb.conf
    env_file:
      - .env
    networks:
      - backend_network

  # Rust Backend API
  backend_api:
    image: rust:1.73
    working_dir: /usr/src/backend_nuitinfo_2023
    volumes:
      - ./api:/usr/src/backend_nuitinfo_2023
    command: ["sh", "-c", "cargo install --path . && cargo run --release"]
    ports: 
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_started
        restart: true
    networks:
      - backend_network
      - user_network

networks:
  backend_network:
    driver: bridge
  user_network:
    driver: bridge